### ISSUE TITLE
BUG: Error on deploy

### ISSUE THREAD

**Issue by jsonpoindexter** [argoapp-live/argo-static-site-deployer#1]
I am currently trying to deploy a Svelte app.

The build process succeeded however, the arweave transaction failed with the following deploy logs:

```bash
08:50:59 AM 05-10-2021: Cloning into 'sushi-bytes-plate-catch'...
08:50:59 AM 05-10-2021: Build started
08:51:00 AM 05-10-2021: Installing packages...
08:51:00 AM 05-10-2021: Clone completed
08:51:00 AM 05-10-2021: No workspace provided
08:51:00 AM 05-10-2021: npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
08:51:08 AM 05-10-2021: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
08:51:08 AM 05-10-2021: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
08:51:08 AM 05-10-2021: added 273 packages from 214 contributors and audited 274 packages in 8.148s
08:51:09 AM 05-10-2021: 44 packages are looking for funding
08:51:09 AM 05-10-2021: run `npm fund` for details
08:51:09 AM 05-10-2021: found 0 vulnerabilities
08:51:09 AM 05-10-2021: Adding relative homepage for correct Arweave deployment for sushi-bytes-plate-catch! 🚀
08:51:09 AM 05-10-2021: Packages installed, Started building app...
08:51:09 AM 05-10-2021: > svelte-app@1.0.0 build /sushi-bytes-plate-catch
08:51:09 AM 05-10-2021: > rollup -c
08:51:09 AM 05-10-2021: src/main.js → public/build/bundle.js...
08:51:11 AM 05-10-2021: (!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
08:51:11 AM 05-10-2021: created public/build/bundle.js in 1.4s
08:51:11 AM 05-10-2021: Starting deploying app...
08:51:11 AM 05-10-2021: Preparing files from /sushi-bytes-plate-catch/public
08:51:12 AM 05-10-2021: ID Size Fee Type Path
08:51:13 AM 05-10-2021: 6K-Sgu04LRPlj7h3ew-9e5h5TM5ipDfJ7xIKFejP3nw 14.62 kB 0.000010473408 image/png assets/platform.png
08:51:13 AM 05-10-2021: Y05ChbV5B1PQ4rm1OdJqt2FbIi_OoQGlfP81qqAvtk8 4.65 kB 0.000004588992 image/png assets/sky.png
08:51:13 AM 05-10-2021: vMyAhfQXLBXuQzXS7c73ABCu9MWqC5AVG5QHWo_4i-c 195.00 Bytes 0.000001961280 text/css global.css
08:51:13 AM 05-10-2021: 2kkqEmmJL3xZkql8l4lNmKYAEWNXIFMAJQ8vznrEeos 10.73 kB 0.000008177472 application/javascript build/bundle.js
08:51:13 AM 05-10-2021: riNA6U0NVPyY1bpFMtK7mtVGLGwhnekwr3tw2FUdtkA 876.00 Bytes 0.000002353536 text/html index.html*
08:51:13 AM 05-10-2021: mZHUxFHR16gwU5wgPByjdgk4EwjgniBZpy3XqBSPhhY 434.00 Bytes 0.000002098944 application/x.arweave-manifest+json
08:51:13 AM 05-10-2021: Summary
08:51:13 AM 05-10-2021: Index: index.html
08:51:13 AM 05-10-2021: Number of files: 5 + 1 manifest
08:51:13 AM 05-10-2021: Total size: 31.04 kB
08:51:13 AM 05-10-2021: Total price: 0.000029653632 AR
08:51:13 AM 05-10-2021: Uploading...
08:51:34 AM 05-10-2021: at Object.onceWrapper (events.js:420:28)
08:51:34 AM 05-10-2021: Error: timeout of 20000ms exceeded
08:51:34 AM 05-10-2021: at ClientRequest.emit (events.js:326:22)
08:51:34 AM 05-10-2021: at createError (/arweave:5629:15)
08:51:34 AM 05-10-2021: at ClientRequest.handleRequestTimeout (/arweave:5002:16)
08:51:34 AM 05-10-2021: at TLSSocket.emitRequestTimeout (_http_client.js:715:9)
08:51:34 AM 05-10-2021: at Object.onceWrapper (events.js:420:28)
08:51:34 AM 05-10-2021: at TLSSocket.emit (events.js:326:22)
08:51:34 AM 05-10-2021: at TLSSocket.Socket._onTimeout (net.js:483:8)
08:51:34 AM 05-10-2021: at listOnTimeout (internal/timers.js:554:17)
08:51:34 AM 05-10-2021: at processTimers (internal/timers.js:497:7) {
08:51:34 AM 05-10-2021: config: {
08:51:34 AM 05-10-2021: url: 'tx',
08:51:34 AM 05-10-2021: method: 'post',
08:51:34 AM 05-10-2021: data: '{"format":2,"id":"mZHUxFHR16gwU5wgPByjdgk4EwjgniBZpy3XqBSPhhY","last_tx":"z6laeC_C6joKBt1WWWZyhBlK5Km3WgMuod_SZmEmEwJxS6QUvEDrNcHjwI-Z1FSm","owner":"vVOQifIXcWlfulaTsHTck76R0UESODkSjOhKwGlotCfvYSDkeBdcA2FrG39JTiS-dkQVF6V476AGxeaOWi-UqwcrEFiTItGeAiZBqJwnCrKNQrAJLk4L5G_2reBnEIGpwerKdg9F88e3k2JQwwCl7MFK0wjDQLmJdL-s5CtZvq8-cxRBXggqOMG3MMlZ8BtXMnJqo4vJGmTanWep7plS662sui-UMoOUpD-bKKQTLSvi8Oc4EaWt13oavNT86q7s9TzOjAGIcKj3GMoA--DAfCU4A9mbm8DdPiduU4HwdbdVNsC0sbHHA3JAyzDojxYzltDHCHyslgvl8P9L98K3bBWFSlmn79hzGNKH6yn9pKS0g4MfcQst1n_EwKXSp6_9PLJTrei6o-NhbCxvUzz-J2FCYcHHSoXpP-fRnNqb7fp1KgmnTKosJs8Ty58VBY83TeW69tWKjKil--zGLGDPoAxHETcz2XrE7yJ8OJAqixF6JP9MWiYx8rLnrKtkkkoHavvntiA95B2x_IkbejUeciUDzwqLfVorGSEv0rLbFvUF3riFxpPv9O6p6qqzTL40Lt-_0vBVYt4CcRXop1wiLkckE2e-n6Feh93ZXyDKN1Zv9KII6an55gsMCDF4T53gLd4TbyN1Y4gVB1I4ijZKTYCTmlU8JPPn_9zo6DMQYl8","tags":[{"name":"Q29udGVudC1UeXBl","value":"YXBwbGljYXRpb24veC5hcndlYXZlLW1hbmlmZXN0K2pzb24"},{"name":"VXNlci1BZ2VudA","value":"QXJ3ZWF2ZURlcGxveS8xLjkuMQ"},{"name":"QXBwLU5hbWU","value":"QXJHb0FwcC8yLjAuMA"}],"target":"","quantity":"0","data":"eyJtYW5pZmVzdCI6ImFyd2VhdmUvcGF0aHMiLCJ2ZXJzaW9uIjoiMC4xLjAiLCJwYXRocyI6eyJhc3NldHMvcGxhdGZvcm0ucG5nIjp7ImlkIjoiNkstU2d1MDRMUlBsajdoM2V3LTllNWg1VE01aXBEZko3eElLRmVqUDNudyJ9LCJhc3NldHMvc2t5LnBuZyI6eyJpZCI6IlkwNUNoYlY1QjFQUTRybTFPZEpxdDJGYklpX09vUUdsZlA4MXFxQXZ0azgifSwiYnVpbGQvYnVuZGxlLmpzIjp7ImlkIjoiMmtrcUVtbUpMM3haa3FsOGw0bE5tS1lBRVdOWElGTUFKUTh2em5yRWVvcyJ9LCJnbG9iYWwuY3NzIjp7ImlkIjoidk15QWhmUVhMQlh1UXpYUzdjNzNBQkN1OU1XcUM1QVZHNVFIV29fNGktYyJ9LCJpbmRleC5odG1sIjp7ImlkIjoicmlOQTZVME5WUHlZMWJwRk10SzdtdFZHTEd3aG5la3dyM3R3MkZVZHRrQSJ9fSwiaW5kZXgiOnsicGF0aCI6ImluZGV4Lmh0bWwifX0","data_size":"434","data_root":"l9uud8DBCLPzt2mOAdCBsfEAgZXBrERIwj4t43EoWk4","reward":"2098944","signature":"ZhBHihUrXU17CE3oTjUPVK4mwMez49V_0vTwMAoMqYS8eMlt69RPdiLU0BWxVHGRuG91NAvLt6UGIgoh4Xo9Q8_-YDS1HPUXEMUxkrjbDmsQUWHAIn49hwmInd51OSTZQRIIlfAD4e3160udKtJqBjIw_h-a09G_CT_eHcZ5d6P3AQ9MOTmz8_oEkUWhDwVMbUZpu1qs4jO4ngWRjYMRLLc7BDZT4HV3eGokjJHMl1q7wha-E7IvkaJPvqqU664IFLXGP4bWznTDZv4rPq33WDfMppeDyPJiy5q3Gnk4NywYBxKhHRZmzCsvdSa52NzfagtJvMVuy56a_SZwDaUY1QzAWeo_fsOtulRjZrSwX9Gce7Up7QB9whLHTdAdls0cjai1QNJAtqeZJaHihOGLz7kERGSVv0EJMDoWzvf_Bjgsex4zstWL0vaEMPaYYAnNPRwiZGtGeX6ZgfTh77yK2S84UT5G_4FX3TiLSKvinCwZXCjfZB5J_ZC_5ZBeI8pQqBO4sR0HjaPam5INOXPadq5RIMbAxDC66iClsQ7mHFU40N2ZiUa2ijThjV_2WLtwMjiHT8fbQ5vKTPF61AUad4eProwvcMkl-5rDzM4Wg-4Ao_dPTPKD7plcvFzholXN3PQ_SawSN03gmwTHwduFbYDK3GvxxddHhWETuGPd4EE"}',
08:51:34 AM 05-10-2021: headers: {
08:51:34 AM 05-10-2021: Accept: 'application/json, text/plain, */*',
08:51:34 AM 05-10-2021: 'Content-Type': 'application/json;charset=utf-8',
08:51:34 AM 05-10-2021: 'User-Agent': 'axios/0.19.2',
08:51:34 AM 05-10-2021: 'Content-Length': 2453
08:51:34 AM 05-10-2021: },
08:51:34 AM 05-10-2021: baseURL: 'https://arweave.net:443',
08:51:34 AM 05-10-2021: transformRequest: [ [Function: transformRequest] ],
08:51:34 AM 05-10-2021: transformResponse: [ [Function: transformResponse] ],
08:51:34 AM 05-10-2021: timeout: 20000,
08:51:34 AM 05-10-2021: xsrfCookieName: 'XSRF-TOKEN',
08:51:34 AM 05-10-2021: adapter: [Function: httpAdapter],
08:51:34 AM 05-10-2021: xsrfHeaderName: 'X-XSRF-TOKEN',
08:51:34 AM 05-10-2021: maxContentLength: 536870912,
08:51:34 AM 05-10-2021: validateStatus: [Function: validateStatus]
08:51:34 AM 05-10-2021: },
08:51:34 AM 05-10-2021: code: 'ECONNABORTED',
08:51:34 AM 05-10-2021: request: Writable {
08:51:34 AM 05-10-2021: _writableState: WritableState {
08:51:34 AM 05-10-2021: objectMode: false,
08:51:34 AM 05-10-2021: highWaterMark: 16384,
08:51:34 AM 05-10-2021: finalCalled: false,
08:51:34 AM 05-10-2021: needDrain: false,
08:51:34 AM 05-10-2021: ending: false,
08:51:34 AM 05-10-2021: ended: false,
08:51:34 AM 05-10-2021: finished: false,
08:51:34 AM 05-10-2021: destroyed: false,
08:51:34 AM 05-10-2021: decodeStrings: true,
08:51:34 AM 05-10-2021: defaultEncoding: 'utf8',
08:51:34 AM 05-10-2021: length: 0,
08:51:34 AM 05-10-2021: writing: false,
08:51:34 AM 05-10-2021: corked: 0,
08:51:34 AM 05-10-2021: sync: true,
08:51:34 AM 05-10-2021: bufferProcessing: false,
08:51:34 AM 05-10-2021: onwrite: [Function: bound onwrite],
08:51:34 AM 05-10-2021: writecb: null,
08:51:34 AM 05-10-2021: writelen: 0,
08:51:34 AM 05-10-2021: afterWriteTickInfo: null,
08:51:34 AM 05-10-2021: bufferedRequest: null,
08:51:34 AM 05-10-2021: lastBufferedRequest: null,
08:51:34 AM 05-10-2021: pendingcb: 0,
08:51:34 AM 05-10-2021: prefinished: false,
08:51:34 AM 05-10-2021: errorEmitted: false,
08:51:34 AM 05-10-2021: emitClose: true,
08:51:34 AM 05-10-2021: autoDestroy: false,
08:51:34 AM 05-10-2021: bufferedRequestCount: 0,
08:51:34 AM 05-10-2021: corkedRequestsFree: [Object]
08:51:34 AM 05-10-2021: },
08:51:34 AM 05-10-2021: writable: true,
08:51:34 AM 05-10-2021: _events: [Object: null prototype] {
08:51:34 AM 05-10-2021: response: [Function: handleResponse],
08:51:34 AM 05-10-2021: error: [Function: handleRequestError]
08:51:34 AM 05-10-2021: },
08:51:34 AM 05-10-2021: _eventsCount: 2,
08:51:34 AM 05-10-2021: _maxListeners: undefined,
08:51:34 AM 05-10-2021: _options: {
08:51:34 AM 05-10-2021: protocol: 'https:',
08:51:34 AM 05-10-2021: maxRedirects: 21,
08:51:34 AM 05-10-2021: maxBodyLength: 536870912,
08:51:34 AM 05-10-2021: path: '/tx',
08:51:34 AM 05-10-2021: method: 'POST',
08:51:34 AM 05-10-2021: headers: [Object],
08:51:34 AM 05-10-2021: agent: undefined,
08:51:34 AM 05-10-2021: agents: [Object],
08:51:34 AM 05-10-2021: auth: undefined,
08:51:34 AM 05-10-2021: hostname: 'arweave.net',
08:51:34 AM 05-10-2021: port: '443',
08:51:34 AM 05-10-2021: nativeProtocols: [Object],
08:51:34 AM 05-10-2021: pathname: '/tx'
08:51:34 AM 05-10-2021: },
08:51:34 AM 05-10-2021: _redirectCount: 0,
08:51:34 AM 05-10-2021: _redirects: [],
08:51:34 AM 05-10-2021: _requestBodyLength: 2453,
08:51:34 AM 05-10-2021: _requestBodyBuffers: [ [Object] ],
08:51:34 AM 05-10-2021: _onNativeResponse: [Function],
08:51:34 AM 05-10-2021: _currentRequest: ClientRequest {
08:51:34 AM 05-10-2021: _events: [Object: null prototype],
08:51:34 AM 05-10-2021: _eventsCount: 6,
08:51:34 AM 05-10-2021: _maxListeners: undefined,
08:51:34 AM 05-10-2021: outputData: [],
08:51:34 AM 05-10-2021: outputSize: 0,
08:51:34 AM 05-10-2021: writable: true,
08:51:34 AM 05-10-2021: _last: true,
08:51:34 AM 05-10-2021: chunkedEncoding: false,
08:51:34 AM 05-10-2021: shouldKeepAlive: false,
08:51:34 AM 05-10-2021: _defaultKeepAlive: true,
08:51:34 AM 05-10-2021: useChunkedEncodingByDefault: true,
08:51:34 AM 05-10-2021: sendDate: false,
08:51:34 AM 05-10-2021: _removedConnection: false,
08:51:34 AM 05-10-2021: _removedContLen: false,
08:51:34 AM 05-10-2021: _removedTE: false,
08:51:34 AM 05-10-2021: _contentLength: null,
08:51:34 AM 05-10-2021: _hasBody: true,
08:51:34 AM 05-10-2021: _trailer: '',
08:51:34 AM 05-10-2021: finished: true,
08:51:34 AM 05-10-2021: _headerSent: true,
08:51:34 AM 05-10-2021: socket: [TLSSocket],
08:51:34 AM 05-10-2021: connection: [TLSSocket],
08:51:34 AM 05-10-2021: _header: 'POST /tx HTTP/1.1\r\n' +
08:51:34 AM 05-10-2021: 'Accept: application/json, text/plain, */*\r\n' +
08:51:34 AM 05-10-2021: 'Content-Type: application/json;charset=utf-8\r\n' +
08:51:34 AM 05-10-2021: 'User-Agent: axios/0.19.2\r\n' +
08:51:34 AM 05-10-2021: 'Content-Length: 2453\r\n' +
08:51:34 AM 05-10-2021: 'Host: arweave.net\r\n' +
08:51:34 AM 05-10-2021: 'Connection: close\r\n' +
08:51:34 AM 05-10-2021: '\r\n',
08:51:34 AM 05-10-2021: _keepAliveTimeout: 0,
08:51:34 AM 05-10-2021: _onPendingData: [Function: noopPendingOutput],
08:51:34 AM 05-10-2021: agent: [Agent],
08:51:34 AM 05-10-2021: socketPath: undefined,
08:51:34 AM 05-10-2021: method: 'POST',
08:51:34 AM 05-10-2021: insecureHTTPParser: undefined,
08:51:34 AM 05-10-2021: path: '/tx',
08:51:34 AM 05-10-2021: _ended: false,
08:51:34 AM 05-10-2021: res: null,
08:51:34 AM 05-10-2021: aborted: true,
08:51:34 AM 05-10-2021: timeoutCb: [Function: emitRequestTimeout],
08:51:34 AM 05-10-2021: upgradeOrConnect: false,
08:51:34 AM 05-10-2021: parser: [HTTPParser],
08:51:34 AM 05-10-2021: maxHeadersCount: null,
08:51:34 AM 05-10-2021: reusedSocket: false,
08:51:34 AM 05-10-2021: host: 'arweave.net',
08:51:34 AM 05-10-2021: protocol: 'https:',
08:51:34 AM 05-10-2021: _redirectable: [Circular],
08:51:34 AM 05-10-2021: [Symbol(kCapture)]: false,
08:51:34 AM 05-10-2021: [Symbol(kNeedDrain)]: false,
08:51:34 AM 05-10-2021: [Symbol(corked)]: 0,
08:51:34 AM 05-10-2021: [Symbol(kOutHeaders)]: [Object: null prototype]
08:51:34 AM 05-10-2021: },
08:51:34 AM 05-10-2021: _currentUrl: 'https://arweave.net:443/tx',
08:51:34 AM 05-10-2021: [Symbol(kCapture)]: false
08:51:34 AM 05-10-2021: },
08:51:34 AM 05-10-2021: response: undefined,
08:51:34 AM 05-10-2021: isAxiosError: true,
08:51:34 AM 05-10-2021: Unable to upload transaction: -1, timeout of 20000ms exceeded
08:51:34 AM 05-10-2021: toJSON: [Function]
08:51:34 AM 05-10-2021: }
```

**Comment by jsonpoindexter** [comment]
Crated a new deploy just now and everything worked! Closing tickets
